import {
  User,
  Location,
  FishSpecies,
  Unit,
  Booking,
  FishBatch,
  Order,
  Payment,
  LeaseContract,
  ImpactRecord,
  MaintenanceLog,
  Partnership,
  Notification,
  ImpactFormula,
  SDGMetric,
} from "./types";

export const INITIAL_USERS: User[] = [
  {
    id: "user-nelayan-anto",
    email: "nelayan.anto@bluesync.id",
    role: "fisherman",
    fullName: "Anto Wijaya (Nelayan Anto)",
    phone: "0812-3456-7890",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    createdAt: "2025-01-10T08:00:00Z",
  },
  {
    id: "user-operator-budi",
    email: "budi@baharijaya.id",
    role: "operator",
    fullName: "Budi Santoso",
    phone: "0813-8899-1122",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    unitId: "unit-01",
    operatorOrg: "BUMDes Bahari Jaya (Muara Baru)",
    createdAt: "2025-01-05T08:00:00Z",
  },
  {
    id: "user-buyer-citra",
    email: "buyer@lautnusantara.co.id",
    role: "buyer",
    fullName: "PT Laut Nusantara (Citra Lestari)",
    phone: "0821-9988-7766",
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    createdAt: "2025-01-15T08:00:00Z",
  },
  {
    id: "user-gov-hendra",
    email: "dinas@kkp.go.id",
    role: "gov",
    fullName: "Dr. Ir. Hendra Wijaya (KKP RI)",
    phone: "0811-2233-4455",
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
    createdAt: "2025-01-02T08:00:00Z",
  },
  {
    id: "user-admin-global",
    email: "admin@bluesync.id",
    role: "admin",
    fullName: "Master Admin BlueSync",
    phone: "0811-0000-9999",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    createdAt: "2025-01-01T08:00:00Z",
  },
];

export const INITIAL_LOCATIONS: Location[] = [
  {
    id: "loc-01",
    villageName: "Desa Muara Baru",
    district: "Penjaringan",
    province: "DKI Jakarta",
    latitude: -6.1084,
    longitude: 106.8041,
    isActive: true,
  },
  {
    id: "loc-02",
    villageName: "Desa Sendangbiru",
    district: "Sumbermanjing Wetan",
    province: "Jawa Timur",
    latitude: -8.4312,
    longitude: 112.6845,
    isActive: true,
  },
  {
    id: "loc-03",
    villageName: "Kelurahan Aertembaga",
    district: "Kota Bitung",
    province: "Sulawesi Utara",
    latitude: 1.4398,
    longitude: 125.1872,
    isActive: true,
  },
  {
    id: "loc-04",
    villageName: "Desa Muncar",
    district: "Banyuwangi",
    province: "Jawa Timur",
    latitude: -8.4333,
    longitude: 114.3333,
    isActive: true,
  },
  {
    id: "loc-05",
    villageName: "Desa Wangi-Wangi",
    district: "Wakatobi",
    province: "Sulawesi Tenggara",
    latitude: -5.3211,
    longitude: 123.5932,
    isActive: true,
  },
];

export const INITIAL_FISH_SPECIES: FishSpecies[] = [
  {
    id: "sp-01",
    name: "Tuna Sirip Kuning",
    localName: "Yellowfin Tuna / Madidihang",
    recommendedTempC: -20,
    maxStorageDays: 14,
    icon: "🐟",
    avgMarketPriceRp: 75000,
    lossRateWithoutColdChainPct: 28,
    lossRateWithColdChainPct: 3,
  },
  {
    id: "sp-02",
    name: "Cakalang",
    localName: "Skipjack Tuna",
    recommendedTempC: -18,
    maxStorageDays: 12,
    icon: "🐠",
    avgMarketPriceRp: 38000,
    lossRateWithoutColdChainPct: 25,
    lossRateWithColdChainPct: 2.5,
  },
  {
    id: "sp-03",
    name: "Tongkol Lisong",
    localName: "Bullet Tuna / Tongkol Krai",
    recommendedTempC: -18,
    maxStorageDays: 10,
    icon: "🐬",
    avgMarketPriceRp: 28000,
    lossRateWithoutColdChainPct: 26,
    lossRateWithColdChainPct: 3,
  },
  {
    id: "sp-04",
    name: "Kakap Merah",
    localName: "Red Snapper / Bambangan",
    recommendedTempC: -18,
    maxStorageDays: 10,
    icon: "🐡",
    avgMarketPriceRp: 85000,
    lossRateWithoutColdChainPct: 22,
    lossRateWithColdChainPct: 2,
  },
  {
    id: "sp-05",
    name: "Kerapu Macan",
    localName: "Tiger Grouper / Kerapu Karang",
    recommendedTempC: -18,
    maxStorageDays: 10,
    icon: "🦈",
    avgMarketPriceRp: 95000,
    lossRateWithoutColdChainPct: 20,
    lossRateWithColdChainPct: 2,
  },
  {
    id: "sp-06",
    name: "Ikan Kembung",
    localName: "Indian Mackerel / Kembung Banjar",
    recommendedTempC: -18,
    maxStorageDays: 7,
    icon: "🦐",
    avgMarketPriceRp: 32000,
    lossRateWithoutColdChainPct: 30,
    lossRateWithColdChainPct: 3.5,
  },
];

export const INITIAL_UNITS: Unit[] = [
  {
    id: "unit-01",
    code: "BS-001",
    name: "BlueSync BD-001 (Bahari Jaya)",
    locationId: "loc-01",
    locationName: "Desa Muara Baru",
    district: "Penjaringan",
    province: "DKI Jakarta",
    capacityKg: 1000,
    currentLoadKg: 720,
    status: "optimal",
    operatorId: "user-operator-budi",
    operatorName: "Budi Santoso (BUMDes Bahari Jaya)",
    installedAt: "2024-11-10",
    solarCapacityKw: 8.4,
    batteryCapacityKwh: 24,
    pricePerKgPerDay: 3500,
    minWeightKg: 5,
    currentTempC: -18.4,
    currentBatteryPct: 88,
    currentSolarKw: 7.8,
    currentGridStatus: "standby",
    compressorOk: true,
    doorOpen: false,
  },
  {
    id: "unit-02",
    code: "BS-002",
    name: "BlueSync SB-002 (Mina Segara)",
    locationId: "loc-02",
    locationName: "Sendangbiru",
    district: "Sumbermanjing Wetan",
    province: "Jawa Timur",
    capacityKg: 1000,
    currentLoadKg: 850,
    status: "optimal",
    operatorId: "user-operator-budi",
    operatorName: "Koperasi Mina Sendangbiru",
    installedAt: "2024-12-01",
    solarCapacityKw: 8.4,
    batteryCapacityKwh: 24,
    pricePerKgPerDay: 3200,
    minWeightKg: 5,
    currentTempC: -19.1,
    currentBatteryPct: 92,
    currentSolarKw: 8.2,
    currentGridStatus: "standby",
    compressorOk: true,
    doorOpen: false,
  },
  {
    id: "unit-03",
    code: "BS-003",
    name: "BlueSync BT-003 (Mina Samudera)",
    locationId: "loc-03",
    locationName: "Aertembaga",
    district: "Kota Bitung",
    province: "Sulawesi Utara",
    capacityKg: 1000,
    currentLoadKg: 910,
    status: "warning",
    operatorId: "user-operator-budi",
    operatorName: "BUMDes Mina Samudera",
    installedAt: "2025-01-05",
    solarCapacityKw: 8.4,
    batteryCapacityKwh: 24,
    pricePerKgPerDay: 3500,
    minWeightKg: 5,
    currentTempC: -14.8,
    currentBatteryPct: 76,
    currentSolarKw: 6.5,
    currentGridStatus: "active",
    compressorOk: true,
    doorOpen: false,
  },
  {
    id: "unit-04",
    code: "BS-004",
    name: "BlueSync MC-004 (Muncar Mandiri)",
    locationId: "loc-04",
    locationName: "Desa Muncar",
    district: "Banyuwangi",
    province: "Jawa Timur",
    capacityKg: 1000,
    currentLoadKg: 450,
    status: "optimal",
    operatorId: "user-operator-budi",
    operatorName: "KUD Mina Mandiri Muncar",
    installedAt: "2025-01-18",
    solarCapacityKw: 8.4,
    batteryCapacityKwh: 24,
    pricePerKgPerDay: 3000,
    minWeightKg: 5,
    currentTempC: -18.7,
    currentBatteryPct: 95,
    currentSolarKw: 8.4,
    currentGridStatus: "standby",
    compressorOk: true,
    doorOpen: false,
  },
  {
    id: "unit-05",
    code: "BS-005",
    name: "BlueSync WK-005 (Bahari Lestari)",
    locationId: "loc-05",
    locationName: "Wangi-Wangi",
    district: "Wakatobi",
    province: "Sulawesi Tenggara",
    capacityKg: 500,
    currentLoadKg: 380,
    status: "optimal",
    operatorId: "user-operator-budi",
    operatorName: "BUMDes Bahari Lestari",
    installedAt: "2025-02-01",
    solarCapacityKw: 4.8,
    batteryCapacityKwh: 12,
    pricePerKgPerDay: 3800,
    minWeightKg: 3,
    currentTempC: -18.2,
    currentBatteryPct: 82,
    currentSolarKw: 4.8,
    currentGridStatus: "standby",
    compressorOk: true,
    doorOpen: false,
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: "bk-01",
    bookingCode: "BS-001-BK01",
    unitId: "unit-01",
    unitCode: "BS-001",
    unitName: "BlueSync BD-001 (Bahari Jaya)",
    fishermanId: "user-nelayan-anto",
    fishermanName: "Anto Wijaya",
    fishermanPhone: "0812-3456-7890",
    fishSpeciesId: "sp-01",
    fishSpeciesName: "Tuna Sirip Kuning",
    weightKg: 50,
    startDate: "2025-08-28",
    endDate: "2025-08-31",
    durationDays: 3,
    status: "active",
    totalPrice: 525000, // 50 * 3 * 3500
    paymentStatus: "paid",
    paymentMethod: "qris",
    notes: "Tangkapan segar pagi hari, kualitas ekspor Grade A",
    createdAt: "2025-08-28T06:30:00Z",
  },
  {
    id: "bk-02",
    bookingCode: "BS-001-BK02",
    unitId: "unit-01",
    unitCode: "BS-001",
    unitName: "BlueSync BD-001 (Bahari Jaya)",
    fishermanId: "user-nelayan-anto",
    fishermanName: "Anto Wijaya",
    fishermanPhone: "0812-3456-7890",
    fishSpeciesId: "sp-02",
    fishSpeciesName: "Cakalang",
    weightKg: 120,
    startDate: "2025-08-26",
    endDate: "2025-08-30",
    durationDays: 4,
    status: "active",
    totalPrice: 1680000,
    paymentStatus: "paid",
    paymentMethod: "qris",
    notes: "Hasil pancing ulur rompong",
    createdAt: "2025-08-26T07:15:00Z",
  },
  {
    id: "bk-03",
    bookingCode: "BS-001-BK03",
    unitId: "unit-01",
    unitCode: "BS-001",
    unitName: "BlueSync BD-001 (Bahari Jaya)",
    fishermanId: "user-nelayan-pak-joko",
    fishermanName: "Joko Santoso",
    fishermanPhone: "0813-1122-3344",
    fishSpeciesId: "sp-04",
    fishSpeciesName: "Kakap Merah",
    weightKg: 80,
    startDate: "2025-08-27",
    endDate: "2025-08-31",
    durationDays: 4,
    status: "active",
    totalPrice: 1120000,
    paymentStatus: "paid",
    paymentMethod: "bank_transfer",
    createdAt: "2025-08-27T08:00:00Z",
  },
  {
    id: "bk-04",
    bookingCode: "BS-001-BK04",
    unitId: "unit-01",
    unitCode: "BS-001",
    unitName: "BlueSync BD-001 (Bahari Jaya)",
    fishermanId: "user-nelayan-pak-rahmat",
    fishermanName: "Rahmat Hidayat",
    fishermanPhone: "0819-5566-7788",
    fishSpeciesId: "sp-03",
    fishSpeciesName: "Tongkol Lisong",
    weightKg: 200,
    startDate: "2025-08-29",
    endDate: "2025-09-01",
    durationDays: 3,
    status: "pending",
    totalPrice: 2100000,
    paymentStatus: "pending",
    paymentMethod: "ewallet",
    createdAt: "2025-08-29T10:00:00Z",
  },
];

export const INITIAL_FISH_BATCHES: FishBatch[] = [
  {
    id: "batch-01",
    batchCode: "BATCH-MUARABARU-TUNA-001",
    bookingId: "bk-01",
    fishermanName: "Anto Wijaya",
    fishSpeciesName: "Tuna Sirip Kuning",
    fishSpeciesId: "sp-01",
    weightKg: 50,
    qrCodeUrl: "/trace/BATCH-MUARABARU-TUNA-001",
    tempHistory: [-18.5, -18.2, -18.7, -18.4, -18.1, -18.6, -18.4],
    freshnessScore: 98,
    entryDate: "2025-08-28T07:00:00Z",
    unitId: "unit-01",
    unitCode: "BS-001",
    unitName: "BlueSync BD-001",
    locationName: "Desa Muara Baru, DKI Jakarta",
    operatorName: "Budi Santoso",
    bumdesName: "BUMDes Bahari Jaya",
    pricePerKg: 78000,
    isAvailableInMarket: true,
    notes: "Tangkapan pancing tonda, daging kenyal kemerahan Grade Sashimi",
  },
  {
    id: "batch-02",
    batchCode: "BATCH-MUARABARU-CAKALANG-002",
    bookingId: "bk-02",
    fishermanName: "Anto Wijaya",
    fishSpeciesName: "Cakalang",
    fishSpeciesId: "sp-02",
    weightKg: 120,
    qrCodeUrl: "/trace/BATCH-MUARABARU-CAKALANG-002",
    tempHistory: [-18.0, -18.3, -18.1, -18.5, -18.2, -18.4],
    freshnessScore: 95,
    entryDate: "2025-08-26T08:00:00Z",
    unitId: "unit-01",
    unitCode: "BS-001",
    unitName: "BlueSync BD-001",
    locationName: "Desa Muara Baru, DKI Jakarta",
    operatorName: "Budi Santoso",
    bumdesName: "BUMDes Bahari Jaya",
    pricePerKg: 42000,
    isAvailableInMarket: true,
    notes: "Kualitas prima, siap pasok restoran & industri pengalengan",
  },
  {
    id: "batch-03",
    batchCode: "BATCH-MALANG-KAKAP-003",
    bookingId: "bk-03",
    fishermanName: "Joko Santoso",
    fishSpeciesName: "Kakap Merah",
    fishSpeciesId: "sp-04",
    weightKg: 80,
    qrCodeUrl: "/trace/BATCH-MALANG-KAKAP-003",
    tempHistory: [-18.9, -19.0, -18.7, -19.2, -18.8],
    freshnessScore: 97,
    entryDate: "2025-08-27T09:00:00Z",
    unitId: "unit-02",
    unitCode: "BS-002",
    unitName: "BlueSync SB-002",
    locationName: "Sendangbiru, Jawa Timur",
    operatorName: "Budi Santoso",
    bumdesName: "Koperasi Mina Sendangbiru",
    pricePerKg: 89000,
    isAvailableInMarket: true,
    notes: "Kakap merah laut dalam, mata jernih insang segar",
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: "ord-01",
    orderCode: "ORD-20250829-001",
    batchId: "batch-01",
    buyerId: "user-buyer-citra",
    buyerName: "PT Laut Nusantara",
    buyerPhone: "0821-9988-7766",
    fishSpeciesName: "Tuna Sirip Kuning",
    quantityKg: 30,
    pricePerKg: 78000,
    totalPrice: 2340000,
    status: "confirmed",
    deliveryAddress: "Kawasan Industri Pergudangan Pluit Blok C-12, Jakarta Utara",
    bumdesName: "BUMDes Bahari Jaya",
    createdAt: "2025-08-29T11:20:00Z",
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: "pay-01",
    bookingId: "bk-01",
    amount: 525000,
    method: "qris",
    status: "paid",
    xenditRef: "XND-QRIS-99281726",
    paidAt: "2025-08-28T06:35:10Z",
    createdAt: "2025-08-28T06:30:00Z",
    description: "Sewa Cold Storage 50kg Tuna (3 Hari)",
    payerName: "Anto Wijaya",
  },
  {
    id: "pay-02",
    bookingId: "bk-02",
    amount: 1680000,
    method: "qris",
    status: "paid",
    xenditRef: "XND-QRIS-88127361",
    paidAt: "2025-08-26T07:20:45Z",
    createdAt: "2025-08-26T07:15:00Z",
    description: "Sewa Cold Storage 120kg Cakalang (4 Hari)",
    payerName: "Anto Wijaya",
  },
  {
    id: "pay-03",
    orderId: "ord-01",
    amount: 2340000,
    method: "bank_transfer",
    status: "paid",
    xenditRef: "XND-VA-55198273",
    paidAt: "2025-08-29T11:25:00Z",
    createdAt: "2025-08-29T11:20:00Z",
    description: "Pembelian 30kg Tuna Sirip Kuning Terverifikasi",
    payerName: "PT Laut Nusantara",
  },
];

export const INITIAL_LEASE_CONTRACTS: LeaseContract[] = [
  {
    id: "lease-01",
    unitId: "unit-01",
    unitCode: "BS-001",
    unitName: "BlueSync BD-001",
    operatorId: "user-operator-budi",
    operatorName: "Budi Santoso",
    bumdesName: "BUMDes Bahari Jaya",
    unitPriceRp: 185000000,
    dpPaidRp: 37000000, // 20%
    monthlyInstallmentRp: 4111111,
    totalMonths: 36,
    remainingMonths: 26,
    progressPct: 38.8,
  },
];

export const INITIAL_IMPACT_RECORDS: ImpactRecord[] = [
  {
    id: "imp-01",
    unitId: "unit-01",
    unitCode: "BS-001",
    locationName: "Desa Muara Baru",
    periodStart: "2025-08-01",
    periodEnd: "2025-08-28",
    kgStored: 750,
    kgLossAvoided: 187.5, // 25% avoided
    revenueRp: 2750000,
    energyKwh: 345,
    co2AvoidedKg: 251.85, // 345 * (0.78 - 0.05)
    fishermenServed: 18,
  },
  {
    id: "imp-02",
    unitId: "unit-02",
    unitCode: "BS-002",
    locationName: "Sendangbiru",
    periodStart: "2025-08-01",
    periodEnd: "2025-08-28",
    kgStored: 890,
    kgLossAvoided: 222.5,
    revenueRp: 2848000,
    energyKwh: 390,
    co2AvoidedKg: 284.7,
    fishermenServed: 22,
  },
  {
    id: "imp-03",
    unitId: "unit-03",
    unitCode: "BS-003",
    locationName: "Bitung",
    periodStart: "2025-08-01",
    periodEnd: "2025-08-28",
    kgStored: 920,
    kgLossAvoided: 230,
    revenueRp: 3220000,
    energyKwh: 310,
    co2AvoidedKg: 226.3,
    fishermenServed: 19,
  },
];

export const INITIAL_MAINTENANCE_LOGS: MaintenanceLog[] = [
  {
    id: "maint-01",
    unitId: "unit-01",
    unitCode: "BS-001",
    reportedBy: "Budi Santoso",
    issueType: "scheduled_inspection",
    severity: "low",
    status: "resolved",
    resolvedAt: "2025-08-20T14:00:00Z",
    notes: "Pembersihan kondensor bulanan dan inspeksi seal pintu refrigerasi. Kondisi optimal.",
    createdAt: "2025-08-20T09:00:00Z",
  },
  {
    id: "maint-02",
    unitId: "unit-03",
    unitCode: "BS-003",
    reportedBy: "Operator Bitung",
    issueType: "compressor",
    severity: "medium",
    status: "in_progress",
    notes: "Fluktuasi suhu terdeteksi pada kompresor inverter. Tim teknisi lokal sedang inspeksi refrigeran R404A.",
    createdAt: "2025-08-29T08:30:00Z",
  },
];

export const INITIAL_PARTNERSHIPS: Partnership[] = [
  {
    id: "part-01",
    partnerName: "Kementerian Kelautan & Perikanan (KKP)",
    type: "pemda",
    province: "Nasional",
    fundingRp: 1500000000,
    targetUnits: 10,
    activeUnits: 5,
    programName: "Program Revitalisasi Cold Chain Nelayan Pesisir 2025",
    contactPerson: "Dr. Hendra Wijaya",
  },
  {
    id: "part-02",
    partnerName: "PT Pertamina (Persero) CSR Bahari Mandiri",
    type: "csr",
    province: "Jawa Timur & DKI Jakarta",
    fundingRp: 850000000,
    targetUnits: 5,
    activeUnits: 3,
    programName: "Desa Energi Berdikari Maritim",
    contactPerson: "Ibu Maya Paramita",
  },
  {
    id: "part-03",
    partnerName: "BUMDes Bahari Jaya Muara Baru",
    type: "bumdes",
    province: "DKI Jakarta",
    fundingRp: 185000000,
    targetUnits: 1,
    activeUnits: 1,
    programName: "Pengembangan Usaha Unit Nelayan Pesisir",
    contactPerson: "Budi Santoso",
  },
];

export const INITIAL_FORMULAS: ImpactFormula[] = [
  {
    id: "form-01",
    name: "Food Loss Avoided",
    formulaKey: "food_loss_avoided",
    formulaExpression: "weight_kg * (loss_rate_without_cold_chain - loss_rate_with_cold_chain)",
    unit: "kg",
    description: "Estimasi bobot ikan yang terselamatkan dari pembusukan berkat pendinginan tepat waktu.",
    isActive: true,
    updatedAt: "2025-08-20T10:00:00Z",
    updatedBy: "Admin BlueSync",
  },
  {
    id: "form-02",
    name: "Economic Value Preserved",
    formulaKey: "economic_value",
    formulaExpression: "food_loss_avoided * avg_price_per_kg_by_species",
    unit: "Rp",
    description: "Nilai ekonomi rupiah yang berhasil dipertahankan dari ikan yang tidak terbuang.",
    isActive: true,
    updatedAt: "2025-08-20T10:00:00Z",
    updatedBy: "Admin BlueSync",
  },
  {
    id: "form-03",
    name: "CO2 Emissions Avoided",
    formulaKey: "co2_avoided",
    formulaExpression: "(solar_kwh * 0.78) - (solar_kwh * 0.05)",
    unit: "kg CO2",
    description: "Reduksi emisi gas rumah kaca berbasis pembangkitan energi surya off-grid versus diesel/grid batubara.",
    isActive: true,
    updatedAt: "2025-08-20T10:00:00Z",
    updatedBy: "Admin BlueSync",
  },
  {
    id: "form-04",
    name: "Renewable Energy Share",
    formulaKey: "renewable_share",
    formulaExpression: "(solar_kwh / total_kwh) * 100",
    unit: "%",
    description: "Proporsi pemakaian energi matahari dari total konsumsi listrik cold storage.",
    isActive: true,
    updatedAt: "2025-08-20T10:00:00Z",
    updatedBy: "Admin BlueSync",
  },
  {
    id: "form-05",
    name: "Fisherman Income Improvement",
    formulaKey: "income_improvement",
    formulaExpression: "economic_value_preserved * 0.65",
    unit: "Rp",
    description: "Tambahan penghasilan bersih yang dinikmati nelayan lokal dari harga jual premium.",
    isActive: true,
    updatedAt: "2025-08-20T10:00:00Z",
    updatedBy: "Admin BlueSync",
  },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: "notif-01",
    targetRole: "operator",
    type: "booking",
    severity: "info",
    title: "Booking Baru Diterima",
    body: "Nelayan Anto memesan 50 kg Tuna Sirip Kuning untuk unit BD-001.",
    isRead: false,
    unitCode: "BS-001",
    createdAt: "2025-08-28T06:30:00Z",
  },
  {
    id: "notif-02",
    targetRole: "all",
    type: "alert",
    severity: "warning",
    title: "Peringatan Suhu Unit BS-003",
    body: "Suhu unit BS-003 Bitung mencapai -14.8°C (ambang batas > -15.0°C). Kompresor sedang stabilisasi.",
    isRead: false,
    unitCode: "BS-003",
    createdAt: "2025-08-29T12:00:00Z",
  },
  {
    id: "notif-03",
    targetRole: "fisherman",
    type: "payment",
    severity: "info",
    title: "Pembayaran QRIS Berhasil",
    body: "Pembayaran sebesar Rp 525.000 untuk booking BS-001-BK01 telah terkonfirmasi.",
    isRead: true,
    createdAt: "2025-08-28T06:35:10Z",
  },
];

export const SDG_METRICS: SDGMetric[] = [
  {
    sdgNumber: 1,
    title: "Tanpa Kemiskinan (No Poverty)",
    tagline: "Peningkatan pendapatan nelayan pesisir",
    targetValue: 25,
    currentValue: 18.5,
    unit: "% kenaikan pendapatan",
    description: "Nelayan menjual ikan segar dengan harga 15-25% lebih tinggi dibanding harga pasar spot pengepul.",
    color: "#E5243B",
  },
  {
    sdgNumber: 2,
    title: "Tanpa Kelaparan (Zero Hunger)",
    tagline: "Penyelamatan pangan & protein hewani laut",
    targetValue: 30,
    currentValue: 25.2,
    unit: "% food loss reduced",
    description: "Menekan angka pembusukan ikan tangkapan dari 29% menjadi kurang dari 4%.",
    color: "#DDA63A",
  },
  {
    sdgNumber: 8,
    title: "Pekerjaan Layak & Pertumbuhan Ekonomi",
    tagline: "Aset produktif dan pendapatan baru BUMDes",
    targetValue: 50,
    currentValue: 42.0,
    unit: "juta Rp/bulan/BUMDes",
    description: "Menciptakan pos pendapatan berkelanjutan bagi pengelola koperasi desa pesisir.",
    color: "#A21942",
  },
  {
    sdgNumber: 9,
    title: "Industri, Inovasi & Infrastruktur",
    tagline: "Desentralisasi cold chain berbasis energi surya",
    targetValue: 50,
    currentValue: 15,
    unit: "unit cold chain",
    description: "Infrastruktur pendingin mikro pintar off-grid yang mandiri dan berketahanan tinggi.",
    color: "#FD6925",
  },
  {
    sdgNumber: 12,
    title: "Konsumsi & Produksi Bertanggung Jawab",
    tagline: "Traceability QR code dari laut ke meja makan",
    targetValue: 100,
    currentValue: 94,
    unit: "% keterlacakan stok",
    description: "Transparansi asal usul tangkapan dan riwayat dingin terjamin secara digital.",
    color: "#BF8B2E",
  },
  {
    sdgNumber: 13,
    title: "Penanganan Perubahan Iklim",
    tagline: "Reduksi emisi karbon melalui solar-hybrid",
    targetValue: 100,
    currentValue: 78.4,
    unit: "ton CO2eq avoided/thn",
    description: "Menggantikan genset diesel dengan sistem PLTS mikro solar PV + baterai LiFePO4.",
    color: "#3F7E44",
  },
  {
    sdgNumber: 14,
    title: "Ekosistem Lautan (Life Below Water)",
    tagline: "Pemanfaatan hasil laut berkelanjutan",
    targetValue: 100,
    currentValue: 88,
    unit: "% ikan terserap bernilai",
    description: "Memastikan setiap ekor ikan yang ditangkap tidak terbuang sia-sia menjadi limbah.",
    color: "#0A97D9",
  },
];
